exchange:
  api:
    key: 0e93de1be2d949089c50165c7edf5913
    urls:
      base: https://openexchangerates.org/api
      currencies: /currencies.json
      latest: /latest.json
      historical: /historical
giphy:
  api:
    key: RlN4m1J3pigZ3886XGFNEB2kQ2OZRgKV
  urls:
    base: https://api.giphy.com/v1/gifs
    search: /search
  q: '{
    1: "rich",
    -1: "broke",
    0: "zero"
  }'
  limit: 20
project:
  urls:
    rate: /api/exchange/rates/rate
    gif: /giphy